### ISSUE TITLE
Tensorflow 1.0 support

### ISSUE THREAD

**Issue by PetroWu** [thtrieu/darkflow#57]
When I upgraded tensorflow from 0.12.1 to 1.0.0, I got the error:

`
Traceback (most recent call last):
  File "./flow", line 42, in <module>
    tfnet = TFNet(FLAGS)
  File "/home/chenxi/workspace/facedet/darkflow/net/build.py", line 50, in __init__
    self.build_forward()
  File "/home/chenxi/workspace/facedet/darkflow/net/build.py", line 70, in build_forward
    state = op_create(*args)
  File "/home/chenxi/workspace/facedet/darkflow/net/ops/__init__.py", line 27, in op_create
    return op_types[layer_type](*args)
  File "/home/chenxi/workspace/facedet/darkflow/net/ops/baseop.py", line 42, in __init__
    self.forward()
  File "/home/chenxi/workspace/facedet/darkflow/net/ops/convolution.py", line 72, in forward
    temp = self.batchnorm(self.lay, temp)
  File "/home/chenxi/workspace/facedet/darkflow/net/ops/convolution.py", line 92, in batchnorm
    return slim.batch_norm(inp, **args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)

TypeError: batch_norm() got an unexpected keyword argument 'initializers'
`

But when I switched the version back to 0.12.1, it worked fine.
Could you please update your tensorflow and fix it?
Thank you for your excellent work!

**Comment by CesarHiersemann** [comment]
This is an easy internal fix if you wanna work with TF 1.0 before the repo gets updates.

I just changed line 88,89,90 in darkflow/net/ops/convolution.py 

from:

v = tf.__version__.split('.')[1]
if int(v) < 12: key = 'initializers'
else: key = 'param_initializers'

to:

v_maj,v_min = tf.__version__.split('.')[:2]
if int(v_maj) < 1 and int(v_min) < 12: key = 'initializers'
else: key = 'param_initializers'

**Comment by CesarHiersemann** [comment]
Nvm, they are actively updating it in:

https://github.com/thtrieu/darkflow/pull/58

**Comment by thtrieu** [comment]
@PetroWu  Tensorflow 1.0 support is the only option now
