### ISSUE TITLE
can it work on python 2.7?

### ISSUE THREAD

**Issue by LiangHao92** [thtrieu/darkflow#350]
the code requests python3 , but my tensorflow is installed on python 2.7, can the code work on python 2.7?

**Comment by tankienleong** [comment]
I use python 2.7 and the code still can work.

**Comment by wcy940418** [comment]
hello @tankienleong , how can you get it work on python 2.7? Thank you in advance

**Comment by LiangHao92** [comment]
@tankienleong  thank you ! I install it successfully, but when I want to translate .weights to .pb ,using
flow --model cfg/yolo-voc.2.0.cfg --load yolo-voc_final.weights --savepb
it said 
AssertionError: expect 268242952 bytes, found 268242956
the .weight and .cfg is trained by my self , and it works well in darknet. what is wrong with it ?

**Comment by LiangHao92** [comment]
@tankienleong  when I tried to save .pb , 2.7 is not very well

**Comment by tankienleong** [comment]
@LiangHao92 I just tried to translate the original YOLOv2 .weights file to .pb and there is no error. Can you please give it a try first?

**Comment by tankienleong** [comment]
Hi @wcy940418 May I know what is the error you faced? I just follow the instructions in the Readme.md file.

**Comment by LiangHao92** [comment]
@tankienleong  really? I have the error 

Traceback (most recent call last):
File "/usr/local/bin/flow", line 6, in
cliHandler(sys.argv)
File "/usr/local/lib/python2.7/dist-packages/darkflow/cli.py", line 35, in cliHandler
tfnet.savepb(); exit('Done')
File "/usr/local/lib/python2.7/dist-packages/darkflow/net/build.py", line 171, in savepb
os.makedirs(os.path.dirname(name), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

I searched this error ,it is said that it's because python is 2.7

**Comment by tankienleong** [comment]
@LiangHao92 replace that line with os.makedirs(os.path.dirname(name), 0777)

**Comment by LiangHao92** [comment]
@tankienleong  thanks a lot !

**Comment by tankienleong** [comment]
@LiangHao92 you are welcome !

**Comment by LiangHao92** [comment]
@tankienleong  have you tried applied .pb to android ? I am tying to use the model I trained on my phone

**Comment by tankienleong** [comment]
@LiangHao92 I haven't try apply .pb to andriod or ios.

**Comment by wcy940418** [comment]
@tankienleong Thank you for your response. I just did not know the error about cython, but I solved it by installing it separately. I think currently the problem is opencv3. Can you get it work with opencv2? I may have to reinstall opencv since the opencv lib is pretty messy on my lab server, I do not know who did it, so I want to make sure which version of opencv I have to install before I install it.

**Comment by LiangHao92** [comment]
@tankienleong hello, I successfully translate .weights to .pb of yolo, but when I tried on tiny-yolo, it said 

labels.txt and cfg/tiny-yolo-voc.cfg indicate inconsistent class numbers

but labels.txt has been changed to be just 1 when I tried on yolo, and the number of classes of yolo and tiny-yolo is the same, how can I get through it?

**Comment by tankienleong** [comment]
@wcy940418 I'm using opencv3.2 and didn't try with opencv2. I recommend you use opencv3 to avoid any compatibility issue.

**Comment by tankienleong** [comment]
@LiangHao92  Did you change the filters in the [convolutional] layer(the second to last layer)?

**Comment by wcy940418** [comment]
@tankienleong Well, apparently, there is no compatibility issue of using opencv2. I already got it work.

**Comment by LiangHao92** [comment]
@tankienleong  thanks a lot. The error occurs because the revise on the tiny-yolo-voc.cfg. I read carefully on the readme, found we should create a new .cfg file rather than revise the original .cfg file:



    Why should I leave the original tiny-yolo-voc.cfg file unchanged?

    When darkflow sees you are loading tiny-yolo-voc.weights it will look for tiny-yolo-voc.cfg in your cfg/ folder and compare that configuration file to the new one you have set with --model cfg/tiny-yolo-voc-3c.cfg. In this case, every layer will have the same exact number of weights except for the last two, so it will load the weights into all layers up to the last two because they now contain different number of weights.

**Comment by GustavZ** [comment]
When i run
`flow --model cfg/tiny-yolo-voc.cfg --load bin/tiny-yolo-voc.weights --savepb`
everything works and the .pb file is created
but if i add the `--gpu 1.0` id gives me following error and i need to close terminal to interrupt it.
![screenshot from 2017-12-14 16-53-47](https://user-images.githubusercontent.com/29252883/34001348-09a19cbc-e0f0-11e7-9153-6e20190afe26.png)
It seems it is something with CUDA, but i am running darknet and tensorflow on other applications with CUDA and there has never been an error (for example google's object detection API)

**Comment by kilsen512** [comment]
@GustavZ In case you haven't figured it out yet. You are running out of GPU memory, try reducing the batch size or the network's size.
